import { Router } from 'express';
import { execFileSync, spawn } from 'child_process';
import path from 'path';
import { existsSync } from 'fs';
import { supabase } from '../supabase.js';
import { requireAuth } from '../auth-middleware.js';
import { cleanupWorktree } from '../worktree.js';
import { git, slugify, commitMessage } from '../git-utils.js';
import { broadcast } from './data.js';
import { agentEnv } from '../runner.js';

export const gitRouter = Router();

// Commit changes
gitRouter.post('/api/git/commit', requireAuth, async (req, res) => {
  const { jobId, localPath } = req.body;

  try {
    const { data: job } = await supabase.from('jobs').select('*, tasks(title, type)').eq('id', jobId).single();
    if (!job) return res.status(404).json({ error: 'Job not found' });

    const task = (job as any).tasks;
    const message = commitMessage(task.type, task.title);

    await git(['add', '-A'], localPath);
    const sha = await git(['commit', '-m', message], localPath);

    res.json({ ok: true, sha, message });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Push to current branch
gitRouter.post('/api/git/push', requireAuth, async (req, res) => {
  const { localPath } = req.body;

  try {
    const output = await git(['push'], localPath, 30000);
    const branch = await git(['branch', '--show-current'], localPath);
    res.json({ ok: true, branch, output });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Create branch + PR
gitRouter.post('/api/git/pr', requireAuth, async (req, res) => {
  const { jobId, localPath } = req.body;

  try {
    const { data: job } = await supabase.from('jobs').select('*, tasks(id, title, type, description)').eq('id', jobId).single();
    if (!job) return res.status(404).json({ error: 'Job not found' });

    const task = (job as any).tasks;
    const shortId = task.id.substring(0, 8);
    const branch = `workstream/${shortId}-${slugify(task.title)}`;
    const message = commitMessage(task.type, task.title);

    // Build PR body from phase outputs
    const phases = (job.phases_completed as any[]) || [];
    let body = `## ${task.title}\n\n${task.description || ''}\n\n`;
    body += `### Phase Outputs\n\n`;
    for (const p of phases) {
      const output = typeof p.output === 'string' ? p.output : JSON.stringify(p.output, null, 2);
      body += `**${p.phase}** (attempt ${p.attempt})\n\`\`\`\n${output.substring(0, 2000)}\n\`\`\`\n\n`;
    }
    body += `---\nGenerated by WorkStream`;

    // Handle existing branch: try checkout, fall back to create
    try {
      await git(['checkout', branch], localPath);
    } catch {
      await git(['checkout', '-b', branch], localPath);
    }

    await git(['add', '-A'], localPath);
    await git(['commit', '-m', message], localPath);
    await git(['push', '-u', 'origin', branch], localPath, 30000);

    const prUrl = execFileSync('gh', ['pr', 'create', '--title', message, '--body', body], {
      cwd: localPath,
      encoding: 'utf-8',
      timeout: 30000,
    }).trim();

    res.json({ ok: true, branch, prUrl });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Review + fix + create PR for a workstream
gitRouter.post('/api/git/workstream-review-pr', requireAuth, async (req, res) => {
  let { workstreamId, localPath } = req.body;
  if (!workstreamId || !localPath) {
    return res.status(400).json({ error: 'workstreamId and localPath are required' });
  }

  // Expand ~ to home directory
  if (localPath.startsWith('~/')) {
    localPath = localPath.replace('~', process.env.HOME || '/home/sixbox');
  }

  try {
    const { data: ws } = await supabase
      .from('workstreams')
      .select('id, name, project_id')
      .eq('id', workstreamId)
      .single();
    if (!ws) return res.status(404).json({ error: 'Workstream not found' });

    // AI CLI is on the task/job level now, default to opencode
    const aiCli = 'opencode';

    // Set workstream status to reviewing
    await supabase.from('workstreams').update({ status: 'reviewing' }).eq('id', workstreamId);

    // Respond immediately — the review runs in the background
    res.json({ ok: true, status: 'reviewing' });

    const slug = slugify(ws.name);
    const branch = `workstream/${slug}`;
    const worktreePath = path.join(localPath, '.worktrees', slug);

    if (!existsSync(worktreePath)) {
      throw new Error(`Worktree not found for workstream at ${worktreePath}`);
    }

    // Step 1: Run code review via opencode/claude -p
    const reviewPrompt = `Use the \`create-pr\` skill to review all changes in this branch, create a Pull Request, wait for the Firebase Preview Channels to deploy, and output the preview URLs. Follow the exact steps in the skill.`;

    await new Promise<string>((resolve, reject) => {
      // Build proper CLI arguments depending on the agent
      let args: string[] = [];
      if (aiCli === 'opencode') {
        args = ['run', '--format', 'json', '-m', 'google/gemini-3.1-pro-preview', reviewPrompt];
      } else {
        args = ['-p', '--output-format', 'text', '--max-turns', '30', '--model', 'opus'];
      }

      const isOpencode = aiCli === 'opencode';
      const spawnEnv = isOpencode ? { ...agentEnv, OPENCODE_AUTO_APPROVE: 'true', OPENCODE_PERMISSION: '{"*":"allow"}' } : agentEnv;

      const proc = spawn(aiCli, args, {
        cwd: worktreePath,
        stdio: ['pipe', 'pipe', 'pipe'],
        env: spawnEnv,
      });
      let stdout = '';
      let stderrTail = '';
      let partialLine = '';
      const STDERR_MAX = 2048;
      let settled = false;

      const timeout = setTimeout(() => {
        if (settled) return;
        settled = true;
        proc.kill();
        reject(new Error(`Review ${aiCli} timed out after 10 minutes. stderr: ${stderrTail}`));
      }, 10 * 60 * 1000);

      proc.stdin.write(reviewPrompt);
      proc.stdin.end();
      proc.stdout.on('data', (d: Buffer) => {
        const text = d.toString();
        stdout += text;
        
        // Parse and log stream events if in JSON mode
        if (aiCli === 'opencode') {
          partialLine += text;
          const lines = partialLine.split('\n');
          partialLine = lines.pop() || '';
          for (const line of lines) {
            if (!line.trim()) continue;
            try {
              const event = JSON.parse(line);
              if (event.type === 'text' && event.part?.text) {
                const txt = event.part.text.trim();
                if (txt) {
                  broadcast(ws.project_id, {
                    type: 'workstream_review_log',
                    workstreamId,
                    text: txt
                  });
                }
              } else if (event.type === 'tool_use' && event.part?.name) {
                broadcast(ws.project_id, {
                  type: 'workstream_review_log',
                  workstreamId,
                  text: `[tool] ${event.part.name}`
                });
              } else if (event.type === 'step_start') {
                 // ignore
              }
            } catch { /* ignore parse errors */ }
          }
        }
      });
      proc.stderr.on('data', (d: Buffer) => {
        stderrTail += d.toString();
        if (stderrTail.length > STDERR_MAX) {
          stderrTail = stderrTail.slice(-STDERR_MAX);
        }
      });
      proc.on('close', (code) => {
        if (settled) return;
        settled = true;
        clearTimeout(timeout);
        if (code === 0 || code === null) resolve(stdout);
        else reject(new Error(`Review ${aiCli} exited with code ${code}. stderr: ${stderrTail}`));
      });
      proc.on('error', (err) => {
        if (settled) return;
        settled = true;
        clearTimeout(timeout);
        reject(err);
      });
    });

    // The AI tool has pushed the branch, created the PR, and outputted the URLs.
    // We just need to extract the PR URL from the gh cli to save to the database.
    let prUrl = '';
    try {
      prUrl = execFileSync('gh', ['pr', 'view', '--json', 'url', '--jq', '.url'], {
        cwd: worktreePath,
        encoding: 'utf-8',
        timeout: 10000,
      }).trim();
    } catch {
      // Fallback if gh pr view fails
    }

    // Update workstream status to done with PR URL
    await supabase.from('workstreams').update({ status: 'complete', pr_url: prUrl || null }).eq('id', workstreamId);

    // Broadcast the completion so the UI updates
    if (ws.project_id) {
      broadcast(ws.project_id, {
        type: 'workstream_reviewed',
        workstreamId,
        prUrl: prUrl || undefined,
      });
    }

    // Cleanup worktree (best-effort)
    try {
      const projectPath = path.dirname(path.dirname(localPath));
      cleanupWorktree(projectPath, slug);
    } catch { /* best-effort */ }

  } catch (err: any) {
    // On failure, set review_failed so UI shows error + retry
    await supabase.from('workstreams').update({ status: 'review_failed' }).eq('id', workstreamId);
    console.error('[review-pr] Failed:', err.message);
  }
});

// Create PR for an entire workstream
gitRouter.post('/api/git/workstream-pr', requireAuth, async (req, res) => {
  const { workstreamId, localPath } = req.body;

  if (!workstreamId || !localPath) {
    return res.status(400).json({ error: 'workstreamId and localPath are required' });
  }

  try {
    // Fetch workstream
    const { data: ws } = await supabase
      .from('workstreams')
      .select('id, name')
      .eq('id', workstreamId)
      .single();
    if (!ws) return res.status(404).json({ error: 'Workstream not found' });

    // Fetch all done tasks for the PR body
    const { data: tasks } = await supabase
      .from('tasks')
      .select('type, title')
      .eq('workstream_id', workstreamId)
      .eq('status', 'done')
      .order('position', { ascending: true });

    const slug = slugify(ws.name);
    const branch = `workstream/${slug}`;
    const title = `workstream: ${ws.name}`;

    // Build PR body from completed tasks
    let body = `## ${ws.name}\n\n### Completed Tasks\n\n`;
    if (tasks && tasks.length > 0) {
      for (const t of tasks) {
        body += `- **${t.type}**: ${t.title}\n`;
      }
    } else {
      body += '_No completed tasks._\n';
    }
    body += `\n---\nGenerated by WorkStream`;

    // Push the worktree branch and create PR
    await git(['push', '-u', 'origin', branch], localPath, 30000);

    const prUrl = execFileSync('gh', ['pr', 'create', '--title', title, '--body', body, '--head', branch], {
      cwd: localPath,
      encoding: 'utf-8',
      timeout: 30000,
    }).trim();

    // Respond first so the client doesn't wait for cleanup
    res.json({ ok: true, branch, prUrl });

    // Clean up the worktree after responding (best-effort)
    try {
      const projectPath = path.dirname(path.dirname(localPath));
      cleanupWorktree(projectPath, slug);
    } catch { /* cleanup is best-effort */ }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});
