import { Router } from 'express';
import { execFileSync, spawn } from 'child_process';
import path from 'path';
import { supabase } from '../supabase.js';
import { requireAuth } from '../auth-middleware.js';
import { cleanupWorktree } from '../worktree.js';
import { git, slugify, commitMessage } from '../git-utils.js';
import { broadcast } from './data.js';
import { claudeEnv } from '../runner.js';

export const gitRouter = Router();

// Commit changes
gitRouter.post('/api/git/commit', requireAuth, async (req, res) => {
  const { jobId, localPath } = req.body;

  try {
    const { data: job } = await supabase.from('jobs').select('*, tasks(title, type)').eq('id', jobId).single();
    if (!job) return res.status(404).json({ error: 'Job not found' });

    const task = (job as any).tasks;
    const message = commitMessage(task.type, task.title);

    await git(['add', '-A'], localPath);
    const sha = await git(['commit', '-m', message], localPath);

    res.json({ ok: true, sha, message });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Push to current branch
gitRouter.post('/api/git/push', requireAuth, async (req, res) => {
  const { localPath } = req.body;

  try {
    const output = await git(['push'], localPath, 30000);
    const branch = await git(['branch', '--show-current'], localPath);
    res.json({ ok: true, branch, output });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Create branch + PR
gitRouter.post('/api/git/pr', requireAuth, async (req, res) => {
  const { jobId, localPath } = req.body;

  try {
    const { data: job } = await supabase.from('jobs').select('*, tasks(id, title, type, description)').eq('id', jobId).single();
    if (!job) return res.status(404).json({ error: 'Job not found' });

    const task = (job as any).tasks;
    const shortId = task.id.substring(0, 8);
    const branch = `codesync/${shortId}-${slugify(task.title)}`;
    const message = commitMessage(task.type, task.title);

    // Build PR body from phase outputs
    const phases = (job.phases_completed as any[]) || [];
    let body = `## ${task.title}\n\n${task.description || ''}\n\n`;
    body += `### Phase Outputs\n\n`;
    for (const p of phases) {
      const output = typeof p.output === 'string' ? p.output : JSON.stringify(p.output, null, 2);
      body += `**${p.phase}** (attempt ${p.attempt})\n\`\`\`\n${output.substring(0, 2000)}\n\`\`\`\n\n`;
    }
    body += `---\nGenerated by CodeSync`;

    // Handle existing branch: try checkout, fall back to create
    try {
      await git(['checkout', branch], localPath);
    } catch {
      await git(['checkout', '-b', branch], localPath);
    }

    await git(['add', '-A'], localPath);
    await git(['commit', '-m', message], localPath);
    await git(['push', '-u', 'origin', branch], localPath, 30000);

    const prUrl = execFileSync('gh', ['pr', 'create', '--title', message, '--body', body], {
      cwd: localPath,
      encoding: 'utf-8',
      timeout: 30000,
    }).trim();

    res.json({ ok: true, branch, prUrl });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Review + fix + create PR for a workstream
gitRouter.post('/api/git/workstream-review-pr', requireAuth, async (req, res) => {
  const { workstreamId, localPath } = req.body;
  if (!workstreamId || !localPath) {
    return res.status(400).json({ error: 'workstreamId and localPath are required' });
  }

  try {
    const { data: ws } = await supabase
      .from('workstreams')
      .select('id, name, project_id')
      .eq('id', workstreamId)
      .single();
    if (!ws) return res.status(404).json({ error: 'Workstream not found' });

    // Set workstream status to reviewing
    await supabase.from('workstreams').update({ status: 'reviewing' }).eq('id', workstreamId);

    // Respond immediately — the review runs in the background
    res.json({ ok: true, status: 'reviewing' });

    const slug = slugify(ws.name);
    const branch = `codesync/${slug}`;

    // Step 1: Run code review via claude -p
    const reviewPrompt = `You are reviewing all changes in this branch before a PR is created.

Run /code-review to review all changes on this branch compared to main.
Then fix any issues that the review identified — apply the fixes directly.
After fixing, run the tests to make sure everything still passes.

At the end, output a brief summary of what was reviewed and what was fixed (if anything).`;

    await new Promise<string>((resolve, reject) => {
      const proc = spawn('claude', ['-p', '--output-format', 'text', '--max-turns', '30', '--model', 'opus'], {
        cwd: localPath,
        stdio: ['pipe', 'pipe', 'pipe'],
        env: claudeEnv,
      });
      let stdout = '';
      let stderrTail = '';
      const STDERR_MAX = 2048;
      let settled = false;

      const timeout = setTimeout(() => {
        if (settled) return;
        settled = true;
        proc.kill();
        reject(new Error(`Review claude timed out after 10 minutes. stderr: ${stderrTail}`));
      }, 10 * 60 * 1000);

      proc.stdin.write(reviewPrompt);
      proc.stdin.end();
      proc.stdout.on('data', (d: Buffer) => { stdout += d.toString(); });
      proc.stderr.on('data', (d: Buffer) => {
        stderrTail += d.toString();
        if (stderrTail.length > STDERR_MAX) {
          stderrTail = stderrTail.slice(-STDERR_MAX);
        }
      });
      proc.on('close', (code) => {
        if (settled) return;
        settled = true;
        clearTimeout(timeout);
        if (code === 0 || code === null) resolve(stdout);
        else reject(new Error(`Review claude exited with code ${code}. stderr: ${stderrTail}`));
      });
      proc.on('error', (err) => {
        if (settled) return;
        settled = true;
        clearTimeout(timeout);
        reject(err);
      });
    });

    // Step 2: Commit any fixes from the review
    try {
      await git(['add', '-A'], localPath);
      await git(['commit', '-m', 'codesync: apply code review fixes'], localPath);
    } catch { /* nothing to commit is fine */ }

    // Step 3: Create the PR
    const { data: tasks } = await supabase
      .from('tasks')
      .select('type, title')
      .eq('workstream_id', workstreamId)
      .eq('status', 'done')
      .order('position', { ascending: true });

    const title = `codesync: ${ws.name}`;
    let body = `## ${ws.name}\n\n### Completed Tasks\n\n`;
    if (tasks && tasks.length > 0) {
      for (const t of tasks) body += `- **${t.type}**: ${t.title}\n`;
    }
    body += `\n_Code reviewed and fixes applied automatically by CodeSync._`;
    body += `\n\n---\nGenerated by CodeSync`;

    await git(['push', '-u', 'origin', branch], localPath, 30000);

    const prUrl = execFileSync('gh', ['pr', 'create', '--title', title, '--body', body, '--head', branch], {
      cwd: localPath,
      encoding: 'utf-8',
      timeout: 30000,
    }).trim();

    // Update workstream status to done with PR URL
    await supabase.from('workstreams').update({ status: 'complete', pr_url: prUrl }).eq('id', workstreamId);

    // Broadcast the completion so the UI updates
    if (ws.project_id) {
      broadcast(ws.project_id, {
        type: 'workstream_reviewed',
        workstreamId,
        prUrl,
      });
    }

    // Cleanup worktree (best-effort)
    try {
      const projectPath = path.dirname(path.dirname(localPath));
      cleanupWorktree(projectPath, slug);
    } catch { /* best-effort */ }

  } catch (err: any) {
    // On failure, set review_failed so UI shows error + retry
    await supabase.from('workstreams').update({ status: 'review_failed' }).eq('id', workstreamId);
    console.error('[review-pr] Failed:', err.message);
  }
});

// Create PR for an entire workstream
gitRouter.post('/api/git/workstream-pr', requireAuth, async (req, res) => {
  const { workstreamId, localPath } = req.body;

  if (!workstreamId || !localPath) {
    return res.status(400).json({ error: 'workstreamId and localPath are required' });
  }

  try {
    // Fetch workstream
    const { data: ws } = await supabase
      .from('workstreams')
      .select('id, name')
      .eq('id', workstreamId)
      .single();
    if (!ws) return res.status(404).json({ error: 'Workstream not found' });

    // Fetch all done tasks for the PR body
    const { data: tasks } = await supabase
      .from('tasks')
      .select('type, title')
      .eq('workstream_id', workstreamId)
      .eq('status', 'done')
      .order('position', { ascending: true });

    const slug = slugify(ws.name);
    const branch = `codesync/${slug}`;
    const title = `codesync: ${ws.name}`;

    // Build PR body from completed tasks
    let body = `## ${ws.name}\n\n### Completed Tasks\n\n`;
    if (tasks && tasks.length > 0) {
      for (const t of tasks) {
        body += `- **${t.type}**: ${t.title}\n`;
      }
    } else {
      body += '_No completed tasks._\n';
    }
    body += `\n---\nGenerated by CodeSync`;

    // Push the worktree branch and create PR
    await git(['push', '-u', 'origin', branch], localPath, 30000);

    const prUrl = execFileSync('gh', ['pr', 'create', '--title', title, '--body', body, '--head', branch], {
      cwd: localPath,
      encoding: 'utf-8',
      timeout: 30000,
    }).trim();

    // Respond first so the client doesn't wait for cleanup
    res.json({ ok: true, branch, prUrl });

    // Clean up the worktree after responding (best-effort)
    try {
      const projectPath = path.dirname(path.dirname(localPath));
      cleanupWorktree(projectPath, slug);
    } catch { /* cleanup is best-effort */ }
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});
